### ISSUE TITLE
Documentation does not describe how to specify Neo4j credentials

### ISSUE THREAD

**Issue by billschuller** [rebar-cloud/rebar-graph#41]
Moving to a _real_ neo4j instance with authentication. Documentation does not specify where credentials should be supplied.

**Comment by billschuller** [comment]
Looks like ENV variables is the answer. They can be passed to Docker with -e flag.

docker run -it \
  -e GRAPH_URL=bolt://FQDN:7687 \
  -e GRAPH_USERNAME = 'rebar' \
  -e GRAPH_PASSWORD = 'foobar' \
  -v $HOME/.aws:/root/.aws:ro \
  rebar/rebar-graph-aws

**Comment by if6was9** [comment]
Fixed here: https://rebar.cloud/aws/
